#!/usr/bin/env python3
# Generate db/words_seed.sql — the canonical catalog of every practiceable word,
# derived from data/pages/ch*.json via render.build_vocab_bank (the same deck the
# pages embed). Import the output in the Supabase SQL editor AFTER running db/schema.sql.
#
#     python3 work/export_words.py        # run from the repo root
#
# Re-run (and re-import) whenever lesson content changes so the catalog stays in
# sync with what the pages quiz. Stdlib only.
import os, glob

# reuse the renderer's bank builder + loaders (importing render does not run main())
from render import build_vocab_bank, load, DATA, ROOT


def sql_str(s):
    return 'NULL' if s is None else "'" + s.replace("'", "''") + "'"


def main():
    rows, seen = [], set()
    pages = sorted(glob.glob(os.path.join(DATA, 'ch*.json')))
    for path in pages:
        page = load(os.path.basename(path))
        slug = page['slug']
        for c in build_vocab_bank(page):
            key = (slug, c['w'])
            if key in seen:
                continue
            seen.add(key)
            rows.append((slug, c['w'], c['r'], c.get('m'), c['t']))

    out = os.path.join(ROOT, 'db', 'words_seed.sql')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as f:
        f.write('-- Generated by work/export_words.py — do not edit by hand.\n')
        f.write('-- Run db/schema.sql first, then paste/run this in the Supabase SQL editor.\n')
        f.write('insert into public.words (slug, word, reading, meaning, type) values\n')
        f.write(',\n'.join(
            f"  ({sql_str(slug)}, {sql_str(w)}, {sql_str(r)}, {sql_str(m)}, {sql_str(t)})"
            for (slug, w, r, m, t) in rows
        ))
        f.write('\non conflict (slug, word) do nothing;\n')
    print(f"db/words_seed.sql: {len(rows)} words from {len(pages)} pages")


if __name__ == '__main__':
    main()
